[package]
name = "rafs"
version = "0.1.0"
authors = ["The Ant Financial Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.17.0"
libc = "0.2"
log = "0.4"
httpdate = "0.3.2"
rust-crypto = "0.2.36"
base64 = "0.11.0"
reqwest = { version = "0.10.4", features = [ "blocking" ] }
url = "2.1.1"
config = "0.10"
compress = "0.1.2"
vm-memory = ">=0.2.0"
fuse-rs = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/fuse-rs.git" }
lazy_static = "1.4.0"
serde = {version = ">=1.0.27", features = ["rc", "serde_derive"] }
serde_derive = ">=1.0.27"
serde_json = ">=1.0.9"

utils = { path = "../utils" }

[features]
fusedev = ["fuse-rs/fusedev"]
virtio-fs = ["fuse-rs/virtiofs"]
vhost-user-fs = ["fuse-rs/vhost-user-fs"]
