[package]
name = "rafs"
version = "0.1.0"
authors = ["The Ant Financial Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
log = "0.4"
fuse = { path = "../fuse" }
serde = "1.0"
vhost_rs = { path = "../vhost_rs" }
vm-memory = {git = "https://github.com/rust-vmm/vm-memory", branch = "master", features = ["backend-mmap"]}
httpdate = "0.3.2"
rust-crypto = "0.2.36"
base64 = "0.11.0"
reqwest = { version = "0.9.24" }
url = "2.1.1"
compress = "0.1.2"

[dependencies.utils]
path = "../utils"
