[package]
name = "nydus-rs"
version = "0.1.0"
authors = ["The Ant Financial Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev_dependencies]
rust-crypto = "0.2.36"

[dependencies]
rlimit = "0.3.0"
log = "0.4"
epoll = ">=4.0.1"
libc = "0.2"
vmm-sys-util = ">=0.3.1"
clap = "2.33"
config = "0.10"
stderrlog = "0.4"
serde_json = "1.0.51"
xattr = "0.2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
rafs = { path = "rafs", features = ["backend-localfs", "backend-oss", "backend-registry"] }
nydus-utils = { path = "utils" }
nydus-builder = { path = "builder" }
nydus-api = { path = "api" }
vm-memory = { version = ">=0.2.0", features = ["backend-mmap"], optional = true }
fuse-rs = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/fuse-backend-rs.git", branch = "nydus", optional = true }
vhost-rs = { git = "https://github.com/cloud-hypervisor/vhost.git", branch = "dragonball", package = "vhost", features = ["vhost-user-slave"], optional = true }
vhost-user-backend = { git = "ssh://git@gitlab.alibaba-inc.com/kata-containers/vhost-user-backend.git", optional = true }

[features]
fusedev = ["nydus-utils/fusedev", "fuse-rs/fusedev"]
virtiofsd = ["fuse-rs/vhost-user-fs", "vm-memory", "vhost-rs", "vhost-user-backend"]

[workspace]
members = [
    "utils",
    "rafs",
    "builder",
    "api",
]
