[package]
name = "nydus-rs"
version = "0.1.0"
authors = ["The Ant Financial Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
epoll = ">=4.0.1"
libc = "0.2.66"
vmm-sys-util = ">=0.3.1"
clap = "2.33"
config = "0.10"
stderrlog = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
vm-memory = {git = "https://github.com/rust-vmm/vm-memory", branch = "master", features = ["backend-mmap"]}

[dependencies.utils]
path = "utils"

[dependencies.rafs]
path = "rafs"

[dependencies.fuse]
path = "fuse"

[dependencies.vhost_rs]
path = "vhost_rs"
features = ["vhost-user-slave"]

[dependencies.image_builder]
path = "image_builder"

[workspace]
members = [
    "utils",
    "rafs",
    "fuse",
    "vhost_rs",
    "image_builder",
]
