[package]
name = "nydus-rs"
version = "0.1.0"
authors = ["The Ant Financial Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlimit = "0.3.0"
log = "0.4"
epoll = ">=4.0.1"
libc = "0.2"
vmm-sys-util = ">=0.3.1"
clap = "2.33"
stderrlog = "0.4"
serde_json = "1.0.51"
sha2 = "0.9.1"
lazy_static = "1.4.0"
xattr = "0.2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
rafs = { path = "rafs", features = ["backend-localfs", "backend-oss", "backend-registry"] }
nydus-utils = { path = "utils" }
nydus-builder = { path = "builder" }
nydus-api = { path = "api" }
vm-memory = { version = ">=0.2.0", optional = true }
fuse-rs = { git = "https://github.com/cloud-hypervisor/fuse-backend-rs.git", optional = true }
vhost-rs = { git = "https://github.com/cloud-hypervisor/vhost.git", branch = "dragonball", package = "vhost", optional = true }
vhost_user_backend = { git = "https://github.com/cloud-hypervisor/vhost-user-backend.git", optional = true }
event-manager = { git = "https://github.com/rust-vmm/event-manager.git", branch= "master" }

[features]
fusedev = ["nydus-utils/fusedev", "fuse-rs/fusedev"]
virtiofsd = ["fuse-rs/vhost-user-fs", "vm-memory/backend-mmap", "vhost-rs/vhost-user-slave", "vhost_user_backend"]

[workspace]
members = [
    "utils",
    "rafs",
    "builder",
    "api",
]
